dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-vpc-flow-log
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-vpc-flow-log v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-vpc-flow-log/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: WxrLVrxaBVIf4bvCHa7z3aLLBhAWvmA1HKheMh35mLsCkQDHIkrEFRPlCIumgowNepb2YIcpj3sl4aKH1xx4Nq/y5KlNig0KFuQsYvSu1QgSFVxjLayRMGFXoiYm0KJ7K30hEcNKmV4/xbGBFMjfIyH8pUOIsqokXnCLlSHcjolh3JpLyFbgj8DMHflROP/lUBNbGLds98nuX31wDl+m0Q3TwuRk90FHv0itG/v4vJX3AeBc2ZNJ3gq3ys8a7uP/SWlLtn0o90t2D6h7i8QQdYCjl/uT29JLGEvhVO1ePaozHC34eqCzFAwjD0hkNmQUo7b5eIL9z+GqMkikoxpPOly7NejMo+p8/BDg3Mtuwh77SsRkWRCRAmdb8ckEqgQdVwSG4B77xoAdsYrOfEYtsvAHwbOJeoRVdCj9olhQmxKR01B+m+WZNOl0o1tEUtnrZ+lwGgf3ZguRxLuOTPM/FNGJ4xxSt+SZTZ2S6g9zXJCdn5VNnbRGTmJyVZakvj91k71oIed9x58upMj08TnogwRpZuRFRDxIq8CuGO0SYuJa8ajm89zm6+QHjkY2oXYlLi0hR27aGMyDe8ciyalRjT0WWLTkxgy4UKHKyFuXDO9tOx8jKoDBFJGm+ANV9INimAq8Y96xOQoSl7UD38Mph8GLaNK3G8yawnWz7yr3BTo=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-vpc-flow-log
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
